CREATE SCHEMA IF NOT EXISTS test1
    AUTHORIZATION postgres;

-- Таблица факультетов
CREATE TABLE IF NOT EXISTS test1.faculty
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    color character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT faculty_pkey PRIMARY KEY (id),
    CONSTRAINT faculty_name_color_unique UNIQUE (name, color)
);

-- Таблица студентов
CREATE TABLE IF NOT EXISTS test1.student
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    age integer DEFAULT 20 CHECK (age >= 16),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL UNIQUE,
    faculty bigint,
    CONSTRAINT student_pkey PRIMARY KEY (id),
    CONSTRAINT faculty_foreign FOREIGN KEY (faculty)
        REFERENCES test1.faculty (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- Таблица аватаров
CREATE TABLE IF NOT EXISTS test1.avatar
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    data oid,
    file_path character varying(255) COLLATE pg_catalog."default",
    file_size bigint,
    media_type character varying(100) COLLATE pg_catalog."default",
    student_id bigint,
    CONSTRAINT avatar_pkey PRIMARY KEY (id),
    CONSTRAINT student_ukey UNIQUE (student_id),
    CONSTRAINT student_foreign_key FOREIGN KEY (student_id)
        REFERENCES test1.student (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
