-- liquibase formatted sql

-- changeset krg:1
CREATE TABLE IF NOT EXISTS faculty (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    color VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT faculty_name_color_unique UNIQUE (name, color)
);

CREATE TABLE IF NOT EXISTS student (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    age INT DEFAULT 20 CHECK (age >= 16),
    name VARCHAR(100) NOT NULL UNIQUE,
    faculty BIGINT,
    CONSTRAINT faculty_foreign FOREIGN KEY (faculty)
        REFERENCES faculty (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS avatar (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    data OID,
    file_path VARCHAR(255),
    file_size BIGINT,
    media_type VARCHAR(100),
    student_id BIGINT,
    CONSTRAINT student_ukey UNIQUE (student_id),
    CONSTRAINT student_foreign_key FOREIGN KEY (student_id)
        REFERENCES student (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- changeset krg:2
CREATE INDEX IF NOT EXISTS idx_student_name ON student (name);

-- changeset krg:3
CREATE INDEX IF NOT EXISTS idx_faculty_name_color ON faculty (name, color);

